//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace k29vnAU.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("k29vnAU.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        internal static string K29VnAuTool_Dl__ {
            get {
                return ResourceManager.GetString("K29VnAuTool_Dl__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0/.
        /// </summary>
        internal static string K29VnAuTool_Dl__0_ {
            get {
                return ResourceManager.GetString("K29VnAuTool_Dl__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang kết nối đến server....
        /// </summary>
        internal static string K29VnAuTool_Dl_Đang_kết_nối_đến_server___ {
            get {
                return ResourceManager.GetString("K29VnAuTool_Dl_Đang_kết_nối_đến_server___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang tải dữ liệu về....
        /// </summary>
        internal static string K29VnAuTool_Dl_Đang_tải_dữ_liệu_về___ {
            get {
                return ResourceManager.GetString("K29VnAuTool_Dl_Đang_tải_dữ_liệu_về___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đường truyền lỗi hoặc đường link file cập nhật chưa chính xác!.
        /// </summary>
        internal static string K29VnAuTool_Dl_Đường_truyền_lỗi_hoặc_đường_link_file_cập_nhật_chưa_chính_xác_ {
            get {
                return ResourceManager.GetString("K29VnAuTool_Dl_Đường_truyền_lỗi_hoặc_đường_link_file_cập_nhật_chưa_chính_xác_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải thành công!.
        /// </summary>
        internal static string K29VnAuTool_Dl_Tải_thành_công_ {
            get {
                return ResourceManager.GetString("K29VnAuTool_Dl_Tải_thành_công_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Bạn vui lòng kiểm tra lại!
        ///
        ///( - Có thể thư mục cài đặt chương trình không phải là : .
        /// </summary>
        internal static string k29vnAuTool_Run_ {
            get {
                return ResourceManager.GetString("k29vnAuTool_Run_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///- Có thể file .
        /// </summary>
        internal static string K29VnAuTool_Run_Cothefile {
            get {
                return ResourceManager.GetString("K29VnAuTool_Run_Cothefile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to đã bị xóa hoặc bị đổi tên )..
        /// </summary>
        internal static string K29VnAuTool_Run_đã_bị_xóa_hoặc_bị_đổi_tên___ {
            get {
                return ResourceManager.GetString("K29VnAuTool_Run_đã_bị_xóa_hoặc_bị_đổi_tên___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang thực hiện cài đặt.
        /// </summary>
        internal static string k29vnAuTool_Run_Đang_thực_hiện_cài_đặt {
            get {
                return ResourceManager.GetString("k29vnAuTool_Run_Đang_thực_hiện_cài_đặt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy file .
        /// </summary>
        internal static string k29vnAuTool_Run_Không_tìm_thấy_file_ {
            get {
                return ResourceManager.GetString("k29vnAuTool_Run_Không_tìm_thấy_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string k29vnAuTool_Run_Thông_báo {
            get {
                return ResourceManager.GetString("k29vnAuTool_Run_Thông_báo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã cài đặt thành công phiên bản mới.
        ///Phiên bản hiện tại: .
        /// </summary>
        internal static string k29vnAuTool_timerStop_Tick_ {
            get {
                return ResourceManager.GetString("k29vnAuTool_timerStop_Tick_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết nối mạng bị lỗi
        ///Bạn vui lòng kiểm tra lại!.
        /// </summary>
        internal static string k29vnAuTool_TimerStopZipTick_ {
            get {
                return ResourceManager.GetString("k29vnAuTool_TimerStopZipTick_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã cập nhật thành công!.
        /// </summary>
        internal static string k29vnAuTool_TimerStopZipTick_Đã_cập_nhật_thành_công_ {
            get {
                return ResourceManager.GetString("k29vnAuTool_TimerStopZipTick_Đã_cập_nhật_thành_công_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn tất quá trình cài đặt phiên bản mới.
        /// </summary>
        internal static string k29vnAuTool_TimerStopZipTick_Hoàn_tất_quá_trình_cài_đặt_phiên_bản_mới {
            get {
                return ResourceManager.GetString("k29vnAuTool_TimerStopZipTick_Hoàn_tất_quá_trình_cài_đặt_phiên_bản_mới", resourceCulture);
            }
        }
    }
}
